// GDN chunked prefill (sm_70): TileLang (MIT, see LICENSE-tilelang) generated code; FlashQLA (MIT) sm70 path of 1Cat-vLLM (Apache-2.0).
// Generated by TileLang 0.1.13 JIT. Captured from the production cache for
// Qwen3.8-27B TP4: Hv=12, Hk=4, D=128, chunk=64, block_DV=32.
// Changes from the generated code: trimmed includes, removed extern "C" and wrapped in a
// namespace, the q/k head index uses ggml's h % Hk GQA mapping instead of h / 3, and the
// per-device head counts Hv/Hk are runtime kernel parameters instead of the TP4 constants.
// ----------------------------------------------------------------------------
#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/instruction/mma_sm70.h>

namespace gdn_chunk_sm70 {

// HV_CT/HK_CT > 0 fix the head counts at compile time (the TP4 shape keeps its constant address
// arithmetic); 0 takes them from Hv_rt/Hk_rt.
template <int HV_CT, int HK_CT>
__global__ void __launch_bounds__(128, 1) tilelang_kkt_solve_kernel_kernel(half_t* __restrict__ a, const float* __restrict__ b, const int* __restrict__ chunk_indices, const int* __restrict__ cu_seqlens, const half_t* __restrict__ k, int num_chunks, int num_tokens, int real_batch_size, int Hv_rt, int Hk_rt) {
  const int Hv = HV_CT > 0 ? HV_CT : Hv_rt;
  const int Hk = HK_CT > 0 ? HK_CT : Hk_rt;
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* a16i_shared = ((void*)((char*)buf_dyn_shmem + 0));
  void* a32i0_shared = ((void*)((char*)buf_dyn_shmem + 0));
  void* a64_shared = ((void*)((char*)buf_dyn_shmem + 0));
  void* k_shared = ((void*)((char*)buf_dyn_shmem + 0));
  void* a32o_shared = ((void*)((char*)buf_dyn_shmem + 4352));
  void* a16o_shared = ((void*)((char*)buf_dyn_shmem + 8448));
  void* a32i1_shared = ((void*)((char*)buf_dyn_shmem + 8448));
  int batch_idx = 0;
  int chunk_idx = 0;
  int seq_start_idx = 0;
  int seq_end_idx = 0;
  __shared__ __align__(16) float b_shared[64];
  float a64_fragment[32];
  float a16i_row[16];
  float a16i_sum[1];
  float a16o_fragment[4];
  float a32i_fragment[16];
  float a32o_fragment[8];
  const int h = (int) (blockIdx.x % (unsigned) Hv);
  const int hk = h % Hk;
  const int64_t k_tok_stride   = (int64_t) Hk * 128;
  const int64_t k_chunk_stride = 64 * k_tok_stride;
  const int64_t k_iter_stride  = 4 * k_tok_stride;
  const int64_t b_tok_stride   = Hv;
  const int64_t b_chunk_stride = 64 * b_tok_stride;
  const int64_t a_tok_stride   = (int64_t) 64 * Hv;
  const int64_t a_chunk_stride = 64 * a_tok_stride;
  const int64_t a_iter_stride  = 16 * a_tok_stride;
  batch_idx = chunk_indices[((((int64_t)((int)blockIdx.x)) / (int64_t)Hv) * (int64_t)2)];
  chunk_idx = chunk_indices[(((((int64_t)((int)blockIdx.x)) / (int64_t)Hv) * (int64_t)2) + (int64_t)1)];
  int condval;
  if (((0 <= batch_idx) && (batch_idx <= real_batch_size))) {
    condval = cu_seqlens[batch_idx];
  } else {
    condval = 0;
  }
  seq_start_idx = condval;
  int condval_1;
  if (((-1 <= batch_idx) && (batch_idx < real_batch_size))) {
    condval_1 = cu_seqlens[(((int64_t)batch_idx) + (int64_t)1)];
  } else {
    condval_1 = 0;
  }
  seq_end_idx = condval_1;
  int batch_idx_1 = batch_idx;
  int chunk_idx_1 = chunk_idx;
  int seq_start_idx_1 = seq_start_idx;
  int seq_end_idx_1 = seq_end_idx;
  if ((((chunk_idx_1 * 64) + seq_start_idx_1) + 64) <= seq_end_idx_1) {
    #pragma unroll
    for (int i = 0; i < 16; ++i) {
      half_t broadcast_var = half_t(0x0p+0f/*0.000000e+00*/);
      uint2 condval_2;
      if (((((((chunk_idx_1 * 64) + (i * 4)) + (((int)threadIdx.x) >> 5)) + seq_start_idx_1) < num_tokens) && (0 <= ((((chunk_idx_1 * 64) + (i * 4)) + (((int)threadIdx.x) >> 5)) + seq_start_idx_1)))) {
        condval_2 = *(uint2*)(k + ((int64_t)chunk_idx_1 * k_chunk_stride + (int64_t)i * k_iter_stride + (int64_t)(threadIdx.x >> 5) * k_tok_stride + (int64_t)seq_start_idx_1 * k_tok_stride + (int64_t)hk * 128 + (int64_t)(threadIdx.x & 31) * 4));
      } else {
        condval_2 = make_uint2(__pack_half2(broadcast_var, broadcast_var), __pack_half2(broadcast_var, broadcast_var));
      }
      *(uint2*)(((half_t*)k_shared) + ((((((((int)threadIdx.x) & 31) * 256) + ((i >> 2) * 64)) + ((((int)threadIdx.x) >> 5) * 16)) + ((((((((int)threadIdx.x) & 7) >> 2) + ((i & 7) >> 2)) + ((i & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 3) >> 1) + (i & 1)) & 1) * 4))) = condval_2;
    }
    if (((int)threadIdx.x) < 64) {
      float condval_3;
      if (((0 <= (((chunk_idx_1 * 64) + seq_start_idx_1) + ((int)threadIdx.x))) && ((((chunk_idx_1 * 64) + seq_start_idx_1) + ((int)threadIdx.x)) < num_tokens))) {
        condval_3 = b[(int64_t)chunk_idx_1 * b_chunk_stride + ((int64_t)seq_start_idx_1 + threadIdx.x) * b_tok_stride + h];
      } else {
        condval_3 = 0x0p+0f/*0.000000e+00*/;
      }
      b_shared[((int)threadIdx.x)] = condval_3;
    }
  } else {
    __syncthreads();
    #pragma unroll
    for (int i_1 = 0; i_1 < 16; ++i_1) {
      if (((((chunk_idx_1 * 64) + (i_1 * 4)) + (((int)threadIdx.x) >> 5)) + seq_start_idx_1) < seq_end_idx_1) {
        half_t broadcast_var_1 = half_t(0x0p+0f/*0.000000e+00*/);
        uint2 condval_4;
        if (((0 <= ((((chunk_idx_1 * 64) + (i_1 * 4)) + (((int)threadIdx.x) >> 5)) + seq_start_idx_1)) && (((((chunk_idx_1 * 64) + (i_1 * 4)) + (((int)threadIdx.x) >> 5)) + seq_start_idx_1) < num_tokens))) {
          condval_4 = *(uint2*)(k + ((int64_t)chunk_idx_1 * k_chunk_stride + (int64_t)i_1 * k_iter_stride + (int64_t)(threadIdx.x >> 5) * k_tok_stride + (int64_t)seq_start_idx_1 * k_tok_stride + (int64_t)hk * 128 + (int64_t)(threadIdx.x & 31) * 4));
        } else {
          condval_4 = make_uint2(__pack_half2(broadcast_var_1, broadcast_var_1), __pack_half2(broadcast_var_1, broadcast_var_1));
        }
        *(uint2*)(((half_t*)k_shared) + ((((((((int)threadIdx.x) & 31) * 256) + ((i_1 >> 2) * 64)) + ((((int)threadIdx.x) >> 5) * 16)) + ((((((i_1 & 7) >> 2) + ((((int)threadIdx.x) & 7) >> 2)) + ((i_1 & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 3) >> 1) + (i_1 & 1)) & 1) * 4))) = condval_4;
      } else {
        half_t broadcast_var_2 = half_t(0x0p+0f/*0.000000e+00*/);
        *(uint2*)(((half_t*)k_shared) + ((((((((int)threadIdx.x) & 31) * 256) + ((i_1 >> 2) * 64)) + ((((int)threadIdx.x) >> 5) * 16)) + ((((((i_1 & 7) >> 2) + ((((int)threadIdx.x) & 7) >> 2)) + ((i_1 & 3) >> 1)) & 1) * 8)) + (((((((int)threadIdx.x) & 3) >> 1) + (i_1 & 1)) & 1) * 4))) = make_uint2(__pack_half2(broadcast_var_2, broadcast_var_2), __pack_half2(broadcast_var_2, broadcast_var_2));
      }
    }
    if (((int)threadIdx.x) < 64) {
      if ((((chunk_idx_1 * 64) + seq_start_idx_1) + ((int)threadIdx.x)) < seq_end_idx_1) {
        float condval_5;
        if (((0 <= (((chunk_idx_1 * 64) + seq_start_idx_1) + ((int)threadIdx.x))) && ((((chunk_idx_1 * 64) + seq_start_idx_1) + ((int)threadIdx.x)) < num_tokens))) {
          condval_5 = b[(int64_t)chunk_idx_1 * b_chunk_stride + ((int64_t)seq_start_idx_1 + threadIdx.x) * b_tok_stride + h];
        } else {
          condval_5 = 0x0p+0f/*0.000000e+00*/;
        }
        b_shared[((int)threadIdx.x)] = condval_5;
      } else {
        b_shared[((int)threadIdx.x)] = 0x0p+0f/*0.000000e+00*/;
      }
    }
  }
  __syncthreads();
  {
    half_t A_local[8];
    half_t B_local[8];
    #pragma unroll
    for (int i_2 = 0; i_2 < 8; ++i_2) {
      float broadcast_var_3 = 0x0p+0f/*0.000000e+00*/;
      *(float4*)(a64_fragment + (i_2 * 4)) = make_float4(broadcast_var_3, broadcast_var_3, broadcast_var_3, broadcast_var_3);
    }
    for (int ki = 0; ki < 32; ++ki) {
      for (int i_3 = 0; i_3 < 2; ++i_3) {
        *(uint2*)(A_local + (i_3 * 4)) = *(uint2*)(((half_t*)k_shared) + ((((((ki * 256) + (((((int)threadIdx.x) & 63) >> 5) * 128)) + (i_3 * 64)) + ((((int)threadIdx.x) & 3) * 16)) + ((((((ki & 7) >> 2) + ((((int)threadIdx.x) & 7) >> 2)) + i_3) & 1) * 8)) + (((((((int)threadIdx.x) & 31) >> 4) + ((ki & 3) >> 1)) & 1) * 4)));
      }
      for (int i_4 = 0; i_4 < 2; ++i_4) {
        *(uint2*)(B_local + (i_4 * 4)) = *(uint2*)(((half_t*)k_shared) + ((((((ki * 256) + ((((int)threadIdx.x) >> 6) * 128)) + (i_4 * 64)) + ((((int)threadIdx.x) & 3) * 16)) + ((((((((int)threadIdx.x) & 31) >> 4) + ((ki & 7) >> 2)) + i_4) & 1) * 8)) + (((((((int)threadIdx.x) & 15) >> 3) + ((ki & 3) >> 1)) & 1) * 4)));
      }
      for (int i_5 = 0; i_5 < 2; ++i_5) {
        for (int j = 0; j < 2; ++j) {
          tl::mma_sync_sm70<tl::DataType::kFloat16, tl::DataType::kFloat16, tl::DataType::kFloat32, 16, 16, 4, false, true>(reinterpret_cast<float*>(a64_fragment + ((i_5 * 16) + (j * 8))), reinterpret_cast<const unsigned*>(A_local + (i_5 * 4)), reinterpret_cast<const unsigned*>(B_local + (j * 4)));
        }
      }
    }
  }
  #pragma unroll
  for (int i_6 = 0; i_6 < 16; ++i_6) {
    float2 __1;
      float2 v_ = *(float2*)(a64_fragment + (i_6 * 2));
      float2 v__1 = make_float2(b_shared[((((((((((int)threadIdx.x) & 63) >> 5) * 32) + ((i_6 >> 3) * 16)) + (((((int)threadIdx.x) & 7) >> 2) * 8)) + (((((int)threadIdx.x) & 31) >> 4) * 4)) + ((i_6 & 1) * 2)) + (((int)threadIdx.x) & 1))], b_shared[((((((((((int)threadIdx.x) & 63) >> 5) * 32) + ((i_6 >> 3) * 16)) + (((((int)threadIdx.x) & 7) >> 2) * 8)) + (((((int)threadIdx.x) & 31) >> 4) * 4)) + ((i_6 & 1) * 2)) + (((int)threadIdx.x) & 1))]);
      __1.x = (v_.x*v__1.x);
      __1.y = (v_.y*v__1.y);
    *(float2*)(a64_fragment + (i_6 * 2)) = __1;
  }
  #pragma unroll
  for (int i_7 = 0; i_7 < 32; ++i_7) {
    if (((((((((((int)threadIdx.x) & 63) >> 5) * 32) + ((i_7 >> 4) * 16)) + (((((int)threadIdx.x) & 7) >> 2) * 8)) + (((((int)threadIdx.x) & 31) >> 4) * 4)) + (((i_7 & 3) >> 1) * 2)) + (((int)threadIdx.x) & 1)) < ((((((((int)threadIdx.x) >> 6) * 32) + (((i_7 & 15) >> 2) * 8)) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_7 & 1))) {
      a64_fragment[i_7] = 0x0p+0f/*0.000000e+00*/;
    } else {
      if (((((((((((int)threadIdx.x) & 63) >> 5) * 32) + ((i_7 >> 4) * 16)) + (((((int)threadIdx.x) & 7) >> 2) * 8)) + (((((int)threadIdx.x) & 31) >> 4) * 4)) + (((i_7 & 3) >> 1) * 2)) + (((int)threadIdx.x) & 1)) == ((((((((int)threadIdx.x) >> 6) * 32) + (((i_7 & 15) >> 2) * 8)) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_7 & 1))) {
        a64_fragment[i_7] = 0x1p+0f/*1.000000e+00*/;
      }
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_8 = 0; i_8 < 32; ++i_8) {
    if ((32 <= (((int)threadIdx.x) & 63)) && (((int)threadIdx.x) < 64)) {
      ((float*)a32o_shared)[((((((((((((((int)threadIdx.x) >> 5) * 1024) + ((i_8 >> 4) * 512)) + (((((int)threadIdx.x) & 7) >> 2) * 256)) + (((((int)threadIdx.x) & 31) >> 4) * 128)) + (((i_8 & 3) >> 1) * 64)) + ((((int)threadIdx.x) & 1) * 32)) + (((i_8 & 15) >> 2) * 8)) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_8 & 1)) - 1024)] = (a64_fragment[i_8] * -0x1p+0f/*-1.000000e+00*/);
    } else {
      if (((((((int)threadIdx.x) & 63) >> 5) * 2) + (i_8 >> 4)) == ((((((int)threadIdx.x) >> 6) * 2) + (((((((i_8 & 15) >> 2) * 8) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_8 & 1)) >> 4)) + 1)) {
        ((float*)a16o_shared)[((((((((((int)threadIdx.x) & 63) >> 5) * 272) + (((((int)threadIdx.x) & 7) >> 2) * 128)) + (((((int)threadIdx.x) & 31) >> 4) * 64)) + (((i_8 & 3) >> 1) * 32)) + ((((int)threadIdx.x) & 1) * 16)) + (((((((i_8 & 15) >> 2) * 8) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_8 & 1)) & 15))] = (a64_fragment[i_8] * -0x1p+0f/*-1.000000e+00*/);
      } else {
        if (((((((int)threadIdx.x) & 63) >> 5) * 2) + (i_8 >> 4)) == (((((int)threadIdx.x) >> 6) * 2) + (((((((i_8 & 15) >> 2) * 8) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_8 & 1)) >> 4))) {
          ((float*)a16i_shared)[(((((((((((int)threadIdx.x) & 63) >> 5) * 544) + ((i_8 >> 4) * 272)) + (((((int)threadIdx.x) & 7) >> 2) * 128)) + (((((int)threadIdx.x) & 31) >> 4) * 64)) + (((i_8 & 3) >> 1) * 32)) + ((((int)threadIdx.x) & 1) * 16)) + (((((((i_8 & 15) >> 2) * 8) + (((((int)threadIdx.x) & 15) >> 3) * 4)) + (((((int)threadIdx.x) & 3) >> 1) * 2)) + (i_8 & 1)) & 15))] = a64_fragment[i_8];
        }
      }
    }
  }
  #pragma unroll
  for (int i_9 = 0; i_9 < 4; ++i_9) {
    float broadcast_var_4 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(a16i_row + (i_9 * 4)) = make_float4(broadcast_var_4, broadcast_var_4, broadcast_var_4, broadcast_var_4);
  }
  __syncthreads();
  #pragma unroll
  for (int k_s = 1; k_s < 16; ++k_s) {
    #pragma unroll
    for (int i_10 = 0; i_10 < 16; ++i_10) {
      if (i_10 < k_s) {
        a16i_row[i_10] = ((float*)a16i_shared)[(((((((int)threadIdx.x) & 63) >> 4) * 272) + (k_s * 16)) + i_10)];
      }
    }
    a16i_sum[0] = 0x0p+0f/*0.000000e+00*/;
    #pragma unroll
    for (int k_r = 0; k_r < k_s; ++k_r) {
      a16i_sum[0] = (a16i_sum[0] - (((float*)a16i_shared)[(((((((int)threadIdx.x) & 63) >> 4) * 272) + (k_r * 16)) + (((int)threadIdx.x) & 15))] * a16i_row[k_r]));
    }
    __syncthreads();
    if ((((int)threadIdx.x) >> 6) == 0) {
      if ((((int)threadIdx.x) & 15) < k_s) {
        ((float*)a16i_shared)[(((((((int)threadIdx.x) & 63) >> 4) * 272) + (k_s * 16)) + (((int)threadIdx.x) & 15))] = a16i_sum[0];
      }
    }
  }
  float broadcast_var_5 = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(a16o_fragment + 0) = make_float4(broadcast_var_5, broadcast_var_5, broadcast_var_5, broadcast_var_5);
  __syncthreads();
  #pragma unroll
  for (int k_r_1 = 0; k_r_1 < 16; ++k_r_1) {
    float4 __2;
      float4 v__2 = *(float4*)(a16o_fragment + 0);
      float4 __3;
        float4 v__3 = make_float4(((float*)a16i_shared)[(((((((int)threadIdx.x) >> 6) * 544) + (((((int)threadIdx.x) & 63) >> 2) * 16)) + k_r_1) + 272)], ((float*)a16i_shared)[(((((((int)threadIdx.x) >> 6) * 544) + (((((int)threadIdx.x) & 63) >> 2) * 16)) + k_r_1) + 272)], ((float*)a16i_shared)[(((((((int)threadIdx.x) >> 6) * 544) + (((((int)threadIdx.x) & 63) >> 2) * 16)) + k_r_1) + 272)], ((float*)a16i_shared)[(((((((int)threadIdx.x) >> 6) * 544) + (((((int)threadIdx.x) & 63) >> 2) * 16)) + k_r_1) + 272)]);
        float4 v__4 = *(float4*)(((float*)a16o_shared) + ((((((int)threadIdx.x) >> 6) * 272) + (k_r_1 * 16)) + ((((int)threadIdx.x) & 3) * 4)));
        __3.x = (v__3.x*v__4.x);
        __3.y = (v__3.y*v__4.y);
        __3.z = (v__3.z*v__4.z);
        __3.w = (v__3.w*v__4.w);
      __2.x = (v__2.x+__3.x);
      __2.y = (v__2.y+__3.y);
      __2.z = (v__2.z+__3.z);
      __2.w = (v__2.w+__3.w);
    *(float4*)(a16o_fragment + 0) = __2;
  }
  __syncthreads();
  #pragma unroll
  for (int i_11 = 0; i_11 < 4; ++i_11) {
    ((float*)a16o_shared)[(((((((int)threadIdx.x) >> 6) * 272) + ((((int)threadIdx.x) & 3) * 64)) + (i_11 * 16)) + ((((int)threadIdx.x) & 63) >> 2))] = a16o_fragment[i_11];
  }
  float broadcast_var_6 = 0x0p+0f/*0.000000e+00*/;
  *(float4*)(a16o_fragment + 0) = make_float4(broadcast_var_6, broadcast_var_6, broadcast_var_6, broadcast_var_6);
  __syncthreads();
  #pragma unroll
  for (int k_r_2 = 0; k_r_2 < 16; ++k_r_2) {
    float4 __4;
      float4 v__5 = *(float4*)(a16o_fragment + 0);
      float4 __5;
        float4 v__6 = make_float4(((float*)a16o_shared)[((((((int)threadIdx.x) >> 6) * 272) + (k_r_2 * 16)) + ((((int)threadIdx.x) & 63) >> 2))], ((float*)a16o_shared)[((((((int)threadIdx.x) >> 6) * 272) + (k_r_2 * 16)) + ((((int)threadIdx.x) & 63) >> 2))], ((float*)a16o_shared)[((((((int)threadIdx.x) >> 6) * 272) + (k_r_2 * 16)) + ((((int)threadIdx.x) & 63) >> 2))], ((float*)a16o_shared)[((((((int)threadIdx.x) >> 6) * 272) + (k_r_2 * 16)) + ((((int)threadIdx.x) & 63) >> 2))]);
        float4 v__7 = *(float4*)(((float*)a16i_shared) + ((((((int)threadIdx.x) >> 6) * 544) + (k_r_2 * 16)) + ((((int)threadIdx.x) & 3) * 4)));
        __5.x = (v__6.x*v__7.x);
        __5.y = (v__6.y*v__7.y);
        __5.z = (v__6.z*v__7.z);
        __5.w = (v__6.w*v__7.w);
      __4.x = (v__5.x+__5.x);
      __4.y = (v__5.y+__5.y);
      __4.z = (v__5.z+__5.z);
      __4.w = (v__5.w+__5.w);
    *(float4*)(a16o_fragment + 0) = __4;
  }
  __syncthreads();
  *(float4*)(((float*)a16o_shared) + (((((int)threadIdx.x) >> 6) * 272) + ((((int)threadIdx.x) & 63) * 4))) = *(float4*)(a16o_fragment + 0);
  #pragma unroll
  for (int i_12 = 0; i_12 < 16; ++i_12) {
    if (((i_12 & 7) < 4) && (4 <= (((int)threadIdx.x) & 7))) {
      a32i_fragment[i_12] = 0x0p+0f/*0.000000e+00*/;
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_13 = 0; i_13 < 4; ++i_13) {
    if (((i_13 & 1) == 1) && ((((int)threadIdx.x) & 7) < 4)) {
      *(float4*)(a32i_fragment + (i_13 * 4)) = *(float4*)(((float*)a16o_shared) + ((((((i_13 >> 1) * 272) + ((i_13 & 1) * 256)) + ((((int)threadIdx.x) >> 3) * 16)) + ((((int)threadIdx.x) & 7) * 4)) - 256));
    }
  }
  #pragma unroll
  for (int i_14 = 0; i_14 < 4; ++i_14) {
    if ((i_14 & 1) == ((((int)threadIdx.x) & 7) >> 2)) {
      *(float4*)(a32i_fragment + (i_14 * 4)) = *(float4*)(((float*)a16i_shared) + (((i_14 * 272) + ((((int)threadIdx.x) >> 3) * 16)) + ((((int)threadIdx.x) & 3) * 4)));
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_15 = 0; i_15 < 4; ++i_15) {
    if ((i_15 >> 1) == 0) {
      *(float4*)(((float*)a32i0_shared) + (((i_15 & 1) * 512) + (((int)threadIdx.x) * 4))) = *(float4*)(a32i_fragment + (i_15 * 4));
    } else {
      *(float4*)(((float*)a32i1_shared) + (((i_15 & 1) * 512) + (((int)threadIdx.x) * 4))) = *(float4*)(a32i_fragment + (i_15 * 4));
    }
  }
  #pragma unroll
  for (int i_16 = 0; i_16 < 2; ++i_16) {
    float broadcast_var_7 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(a32o_fragment + (i_16 * 4)) = make_float4(broadcast_var_7, broadcast_var_7, broadcast_var_7, broadcast_var_7);
  }
  __syncthreads();
  for (int k_r_3 = 0; k_r_3 < 32; ++k_r_3) {
    #pragma unroll
    for (int i_17 = 0; i_17 < 2; ++i_17) {
      float4 __6;
        float4 v__8 = *(float4*)(a32o_fragment + (i_17 * 4));
        float4 __7;
          float4 v__9 = make_float4(((float*)a32i1_shared)[(((i_17 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_3)], ((float*)a32i1_shared)[(((i_17 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_3)], ((float*)a32i1_shared)[(((i_17 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_3)], ((float*)a32i1_shared)[(((i_17 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_3)]);
          float4 v__10 = *(float4*)(((float*)a32o_shared) + ((k_r_3 * 32) + ((((int)threadIdx.x) & 7) * 4)));
          __7.x = (v__9.x*v__10.x);
          __7.y = (v__9.y*v__10.y);
          __7.z = (v__9.z*v__10.z);
          __7.w = (v__9.w*v__10.w);
        __6.x = (v__8.x+__7.x);
        __6.y = (v__8.y+__7.y);
        __6.z = (v__8.z+__7.z);
        __6.w = (v__8.w+__7.w);
      *(float4*)(a32o_fragment + (i_17 * 4)) = __6;
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_18 = 0; i_18 < 2; ++i_18) {
    *(float4*)(((float*)a32o_shared) + ((i_18 * 512) + (((int)threadIdx.x) * 4))) = *(float4*)(a32o_fragment + (i_18 * 4));
  }
  #pragma unroll
  for (int i_19 = 0; i_19 < 2; ++i_19) {
    float broadcast_var_8 = 0x0p+0f/*0.000000e+00*/;
    *(float4*)(a32o_fragment + (i_19 * 4)) = make_float4(broadcast_var_8, broadcast_var_8, broadcast_var_8, broadcast_var_8);
  }
  __syncthreads();
  for (int k_r_4 = 0; k_r_4 < 32; ++k_r_4) {
    #pragma unroll
    for (int i_20 = 0; i_20 < 2; ++i_20) {
      float4 __8;
        float4 v__11 = *(float4*)(a32o_fragment + (i_20 * 4));
        float4 __9;
          float4 v__12 = make_float4(((float*)a32o_shared)[(((i_20 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_4)], ((float*)a32o_shared)[(((i_20 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_4)], ((float*)a32o_shared)[(((i_20 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_4)], ((float*)a32o_shared)[(((i_20 * 512) + ((((int)threadIdx.x) >> 3) * 32)) + k_r_4)]);
          float4 v__13 = *(float4*)(((float*)a32i0_shared) + ((k_r_4 * 32) + ((((int)threadIdx.x) & 7) * 4)));
          __9.x = (v__12.x*v__13.x);
          __9.y = (v__12.y*v__13.y);
          __9.z = (v__12.z*v__13.z);
          __9.w = (v__12.w*v__13.w);
        __8.x = (v__11.x+__9.x);
        __8.y = (v__11.y+__9.y);
        __8.z = (v__11.z+__9.z);
        __8.w = (v__11.w+__9.w);
      *(float4*)(a32o_fragment + (i_20 * 4)) = __8;
    }
  }
  __syncthreads();
  #pragma unroll
  for (int i_21 = 0; i_21 < 4; ++i_21) {
    half_t a64_shared_local_cast[4];
    uint2 __10;
    float4 v__14 = *(float4*)(a32i_fragment + (i_21 * 4));
    ((half2*)(&__10))[0] = __float22half2_rn(((float2*)(&v__14))[0]);
    ((half2*)(&__10))[1] = __float22half2_rn(((float2*)(&v__14))[1]);
    *(uint2*)(a64_shared_local_cast + 0) = __10;
    *(uint2*)(((half_t*)a64_shared) + ((((i_21 * 1024) + ((((int)threadIdx.x) >> 3) * 64)) + ((i_21 >> 1) * 32)) + ((((int)threadIdx.x) & 7) * 4))) = *(uint2*)(a64_shared_local_cast + 0);
  }
  #pragma unroll
  for (int i_22 = 0; i_22 < 2; ++i_22) {
    half_t a64_shared_local_cast_1[4];
    uint2 __11;
    float4 v__15 = *(float4*)(a32o_fragment + (i_22 * 4));
    ((half2*)(&__11))[0] = __float22half2_rn(((float2*)(&v__15))[0]);
    ((half2*)(&__11))[1] = __float22half2_rn(((float2*)(&v__15))[1]);
    *(uint2*)(a64_shared_local_cast_1 + 0) = __11;
    *(uint2*)(((half_t*)a64_shared) + ((((i_22 * 1024) + ((((int)threadIdx.x) >> 3) * 64)) + ((((int)threadIdx.x) & 7) * 4)) + 2048)) = *(uint2*)(a64_shared_local_cast_1 + 0);
  }
  half_t broadcast_var_9 = half_t(0x0p+0f/*0.000000e+00*/);
  *(uint4*)(((half_t*)a64_shared) + ((((((int)threadIdx.x) >> 2) * 64) + ((((int)threadIdx.x) & 3) * 8)) + 32)) = make_uint4(__pack_half2(broadcast_var_9, broadcast_var_9), __pack_half2(broadcast_var_9, broadcast_var_9), __pack_half2(broadcast_var_9, broadcast_var_9), __pack_half2(broadcast_var_9, broadcast_var_9));
  __syncthreads();
  if ((((chunk_idx_1 * 64) + seq_start_idx_1) + 64) <= seq_end_idx_1) {
    #pragma unroll
    for (int i_23 = 0; i_23 < 4; ++i_23) {
      if ((((((chunk_idx_1 * 64) + (i_23 * 16)) + (((int)threadIdx.x) >> 3)) + seq_start_idx_1) < num_tokens) && (0 <= ((((chunk_idx_1 * 64) + (i_23 * 16)) + (((int)threadIdx.x) >> 3)) + seq_start_idx_1))) {
        *(uint4*)(a + ((int64_t)chunk_idx_1 * a_chunk_stride + (int64_t)i_23 * a_iter_stride + (int64_t)(threadIdx.x >> 3) * a_tok_stride + (int64_t)seq_start_idx_1 * a_tok_stride + (int64_t)h * 64 + (int64_t)(threadIdx.x & 7) * 8)) = *(uint4*)(((half_t*)a64_shared) + ((i_23 * 1024) + (((int)threadIdx.x) * 8)));
      }
    }
  } else {
    #pragma unroll
    for (int i_24 = 0; i_24 < 4; ++i_24) {
      if (((((chunk_idx_1 * 64) + (i_24 * 16)) + (((int)threadIdx.x) >> 3)) + seq_start_idx_1) < seq_end_idx_1) {
        if (0 <= ((((chunk_idx_1 * 64) + (i_24 * 16)) + (((int)threadIdx.x) >> 3)) + seq_start_idx_1)) {
          if (((((chunk_idx_1 * 64) + (i_24 * 16)) + (((int)threadIdx.x) >> 3)) + seq_start_idx_1) < num_tokens) {
            *(uint4*)(a + ((int64_t)chunk_idx_1 * a_chunk_stride + (int64_t)i_24 * a_iter_stride + (int64_t)(threadIdx.x >> 3) * a_tok_stride + (int64_t)seq_start_idx_1 * a_tok_stride + (int64_t)h * 64 + (int64_t)(threadIdx.x & 7) * 8)) = *(uint4*)(((half_t*)a64_shared) + ((i_24 * 1024) + (((int)threadIdx.x) * 8)));
          }
        }
      }
    }
  }
}

} // namespace gdn_chunk_sm70

