// GDN chunked prefill (sm_70): TileLang (MIT, see LICENSE-tilelang) generated code; FlashQLA (MIT) sm70 path of 1Cat-vLLM (Apache-2.0).
// Generated by TileLang 0.1.13 JIT. Captured from the production cache for
// Qwen3.8-27B TP4: Hv=12, Hk=4, D=128, chunk=64, block_DV=32.
// Changes from the generated code: trimmed includes, removed extern "C" and wrapped in a
// namespace, and the q/k head index uses ggml's h % 4 GQA mapping instead of h / 3.
// ----------------------------------------------------------------------------
#if defined(_MSC_VER) && !defined(__clang__) && _MSC_VER < 1940
#define _tl_orig_alignas alignas
#define alignas(N) _tl_orig_alignas((N) <= 64 ? (N) : 64)
#include <cuda.h>
#undef alignas
#define alignas _tl_orig_alignas
#endif
#include <tl_templates/cuda/scan.h>

namespace gdn_chunk_sm70 {

__global__ void __launch_bounds__(128, 1) tilelang_chunk_local_cumsum_kernel_kernel(const int* __restrict__ chunk_indices, const int* __restrict__ cu_seqlens, float* __restrict__ g_cumsum, const float* __restrict__ g_raw, int num_chunks, int num_tokens, int real_batch_size) {
  extern __shared__ __align__(1024) uchar buf_dyn_shmem[];
  void* gT_shared = ((void*)((char*)buf_dyn_shmem + 0));
  void* scan_smem = ((void*)((char*)buf_dyn_shmem + 3328));
  float gT_fragment[6];
  float src_buffer[6];
  int batch_idx = chunk_indices[(((int64_t)((int)blockIdx.x)) * (int64_t)2)];
  int chunk_idx = chunk_indices[((((int64_t)((int)blockIdx.x)) * (int64_t)2) + (int64_t)1)];
  int condval;
  if (((0 <= batch_idx) && (batch_idx <= real_batch_size))) {
    condval = cu_seqlens[((int64_t)batch_idx)];
  } else {
    condval = 0;
  }
  int seq_start_idx = condval;
  int condval_1;
  if (((-1 <= batch_idx) && (batch_idx < real_batch_size))) {
    condval_1 = cu_seqlens[(((int64_t)batch_idx) + (int64_t)1)];
  } else {
    condval_1 = 0;
  }
  int seq_end_idx = condval_1;
  if ((((chunk_idx * 64) + seq_start_idx) + 64) <= seq_end_idx) {
    #pragma unroll
    for (int i = 0; i < 3; ++i) {
      float broadcast_var = 0x0p+0f/*0.000000e+00*/;
      float2 condval_2;
      if ((((((chunk_idx * 64) + (((i * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < num_tokens) && (0 <= (((chunk_idx * 64) + (((i * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx)))) {
        condval_2 = *(float2*)(g_raw + ((((((int64_t)chunk_idx) * (int64_t)768) + (((int64_t)i) * (int64_t)256)) + (((int64_t)seq_start_idx) * (int64_t)12)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)));
      } else {
        condval_2 = make_float2(broadcast_var, broadcast_var);
      }
      *(float2*)(gT_fragment + (i * 2)) = condval_2;
    }
  } else {
    #pragma unroll
    for (int i_1 = 0; i_1 < 3; ++i_1) {
      if ((((chunk_idx * 64) + (((i_1 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < seq_end_idx) {
        float broadcast_var_1 = 0x0p+0f/*0.000000e+00*/;
        float2 condval_3;
        if (((0 <= (((chunk_idx * 64) + (((i_1 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx)) && ((((chunk_idx * 64) + (((i_1 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < num_tokens))) {
          condval_3 = *(float2*)(g_raw + ((((((int64_t)chunk_idx) * (int64_t)768) + (((int64_t)i_1) * (int64_t)256)) + (((int64_t)seq_start_idx) * (int64_t)12)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2)));
        } else {
          condval_3 = make_float2(broadcast_var_1, broadcast_var_1);
        }
        *(float2*)(gT_fragment + (i_1 * 2)) = condval_3;
      } else {
        float broadcast_var_2 = 0x0p+0f/*0.000000e+00*/;
        *(float2*)(gT_fragment + (i_1 * 2)) = make_float2(broadcast_var_2, broadcast_var_2);
      }
    }
  }
  #pragma unroll
  for (int i_2 = 0; i_2 < 6; ++i_2) {
    ((float*)gT_shared)[(((((((i_2 >> 1) * 64) + (((int)threadIdx.x) >> 1)) / 3) * 13) + (((((i_2 >> 1) * 128) + ((int)threadIdx.x)) % 6) * 2)) + (i_2 & 1))] = gT_fragment[i_2];
  }
  __syncthreads();
  #pragma unroll
  for (int i_3 = 0; i_3 < 6; ++i_3) {
    src_buffer[i_3] = ((float*)gT_shared)[((((((int)threadIdx.x) & 63) * 13) + (i_3 * 2)) + (((int)threadIdx.x) >> 6))];
  }
  #pragma unroll
  for (int i_4 = 0; i_4 < 6; ++i_4) {
    ((float*)scan_smem)[((i_4 * 128) + ((int)threadIdx.x))] = src_buffer[i_4];
  }
  __syncthreads();
  tl::CumSum2D<128, 1, false>::run((&(((float*)scan_smem)[0])), (&(((float*)scan_smem)[0])), 12, 64, 64, 64);
  __syncthreads();
  #pragma unroll
  for (int i_5 = 0; i_5 < 6; ++i_5) {
    src_buffer[i_5] = ((float*)scan_smem)[((i_5 * 128) + ((int)threadIdx.x))];
  }
  #pragma unroll
  for (int i_6 = 0; i_6 < 6; ++i_6) {
    ((float*)gT_shared)[((((((int)threadIdx.x) & 63) * 13) + (i_6 * 2)) + (((int)threadIdx.x) >> 6))] = src_buffer[i_6];
  }
  __syncthreads();
  #pragma unroll
  for (int i_7 = 0; i_7 < 6; ++i_7) {
    gT_fragment[i_7] = ((float*)gT_shared)[(((((((i_7 >> 1) * 64) + (((int)threadIdx.x) >> 1)) / 3) * 13) + (((((i_7 >> 1) * 128) + ((int)threadIdx.x)) % 6) * 2)) + (i_7 & 1))];
  }
  if ((((chunk_idx * 64) + seq_start_idx) + 64) <= seq_end_idx) {
    #pragma unroll
    for (int i_8 = 0; i_8 < 3; ++i_8) {
      if (((((chunk_idx * 64) + (((i_8 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < num_tokens) && (0 <= (((chunk_idx * 64) + (((i_8 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx))) {
        *(float2*)(g_cumsum + ((((((int64_t)chunk_idx) * (int64_t)768) + (((int64_t)i_8) * (int64_t)256)) + (((int64_t)seq_start_idx) * (int64_t)12)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2))) = *(float2*)(gT_fragment + (i_8 * 2));
      }
    }
  } else {
    #pragma unroll
    for (int i_9 = 0; i_9 < 3; ++i_9) {
      if ((((chunk_idx * 64) + (((i_9 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < seq_end_idx) {
        if (0 <= (((chunk_idx * 64) + (((i_9 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx)) {
          if ((((chunk_idx * 64) + (((i_9 * 64) + (((int)threadIdx.x) >> 1)) / 3)) + seq_start_idx) < num_tokens) {
            *(float2*)(g_cumsum + ((((((int64_t)chunk_idx) * (int64_t)768) + (((int64_t)i_9) * (int64_t)256)) + (((int64_t)seq_start_idx) * (int64_t)12)) + (((int64_t)((int)threadIdx.x)) * (int64_t)2))) = *(float2*)(gT_fragment + (i_9 * 2));
          }
        }
      }
    }
  }
}

} // namespace gdn_chunk_sm70

